eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
spring:
  cloud:
    config:
      override-system-properties: false
#application:
#  config:
#    customer-url: http://localhost:8090/api/v1/customers
#    payment-url: http://localhost:8060/api/v1/payments
#    product-url: http://localhost:8050/api/v1/products
